return {
  { "nvim-pack/nvim-spectre", enabled = false },
  { "dstein64/vim-startuptime", enabled = false },
  { "rafamadriz/friendly-snippets", enabled = false },
  { "echasnovski/mini.ai", enabled = false },
  { "RRethy/vim-illuminate", enabled = false },
  { "folke/persistence.nvim", enabled = false },
  { "nvimdev/dashboard-nvim", enabled = false },
  { "gbprod/yanky.nvim", enabled = false },
  { "stevearc/aerial.nvim", enabled = false },
  { "ggandor/flit.nvim", enabled = false },
  { "ggandor/leap.nvim", enabled = false },
  { "folke/noice.nvim", enabled = false },
  { "echasnovski/mini.surround", enabled = false },
  { "rcarriga/nvim-notify", enabled = false },
  { "stevearc/dressing.nvim", enabled = false },
  -- { "nvim-neo-tree/neo-tree.nvim", enabled = false },
  -- { "MunifTanjim/nui.nvim", enabled = false },
  { "echasnovski/mini.indentscope", enabled = false },
}
